[package]
name = "caramelo-macros"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Caramelo macros"
readme = "README.md"
license.workspace = true
keywords = ["testing", "assertions", "matchers"]
publish = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
caramelo = { workspace = true }